"""
Метаданные для остальных блоков (3-10), проекты, достижения, вопросы собеседований.
Блоки 1 и 2 имеют полный контент в отдельных модулях.
"""
from typing import Any


# ============================================================================
# Блоки 1-10 (метаданные)
# ============================================================================
BLOCKS_META: list[dict[str, Any]] = [
    {
        "number": 1,
        "title": "Python для Data Science",
        "description": "Основы языка Python: переменные, циклы, функции, списки, словари, файлы, CSV, обработка ошибок. Тема — Космос.",
        "theme": "space",
        "lessons_meta": [],  # Заполняется из реальных уроков
    },
    {
        "number": 2,
        "title": "SQL для Data Science",
        "description": "SELECT, JOIN, GROUP BY, оконные функции, CTE, подзапросы, оптимизация. Тема — Видеоигры.",
        "theme": "gaming",
        "lessons_meta": [],
    },
    {
        "number": 3,
        "title": "NumPy и Pandas",
        "description": "Работа с массивами, таблицами, очистка данных, агрегация, merge, временные ряды.",
        "theme": "mixed",
        "lessons_meta": [
            "NumPy: массивы и операции",
            "NumPy: индексация, срезы, маски",
            "Pandas: Series и DataFrame",
            "Импорт данных: CSV, JSON, Excel",
            "Фильтрация и выборка данных",
            "Очистка данных: пропуски",
            "Очистка данных: дубликаты и выбросы",
            "Агрегации и groupby",
            "Merge и Join в Pandas",
            "Преобразование данных: pivot, melt, stack",
            "Работа с датами и временными рядами",
            "Мини-проект: Очистка и подготовка реального датасета",
        ],
    },
    {
        "number": 4,
        "title": "Визуализация данных",
        "description": "Matplotlib, Seaborn, типы графиков, дашборды. Тема — Космос.",
        "theme": "space",
        "lessons_meta": [
            "Matplotlib: основы",
            "Типы графиков: линейный, столбчатый, круговой",
            "Scatter plot и корреляционные диаграммы",
            "Гистограммы и box plot",
            "Seaborn: статистические визуализации",
            "Heatmap и pairplot",
            "Как выбрать правильный тип графика",
            "Оформление и стиль: цвета, заголовки, легенды",
            "Сторителлинг с данными",
            "Мини-проект: Дашборд анализа космической миссии",
        ],
    },
    {
        "number": 5,
        "title": "Статистика для Data Science",
        "description": "Описательная статистика, распределения, корреляция, гипотезы, A/B тесты.",
        "theme": "mixed",
        "lessons_meta": [
            "Описательная статистика: среднее, медиана, мода",
            "Дисперсия, стандартное отклонение, IQR",
            "Типы распределений",
            "Корреляция и причинно-следственные связи",
            "Центральная предельная теорема",
            "Доверительные интервалы",
            "Гипотезы и p-value",
            "A/B тестирование: теория",
            "A/B тестирование: практика",
            "Мини-проект: A/B тест новой механики в игре",
        ],
    },
    {
        "number": 6,
        "title": "EDA — Исследовательский анализ данных",
        "description": "Полный цикл исследовательского анализа. Тема — Космос.",
        "theme": "space",
        "lessons_meta": [
            "Что такое EDA и зачем он нужен",
            "Первичный осмотр датасета",
            "Анализ числовых переменных",
            "Анализ категориальных переменных",
            "Анализ взаимосвязей между переменными",
            "Обнаружение аномалий и выбросов",
            "Формулировка гипотез по данным",
            "Мини-проект: Полный EDA датасета SpaceX миссий",
        ],
    },
    {
        "number": 7,
        "title": "Машинное обучение",
        "description": "Supervised/unsupervised, метрики, регрессия, классификация, деревья, ансамбли, кластеризация.",
        "theme": "mixed",
        "lessons_meta": [
            "Типы ML: supervised, unsupervised, reinforcement",
            "Train/Test Split и кросс-валидация",
            "Переобучение и недообучение",
            "Метрики регрессии: MAE, MSE, RMSE, R²",
            "Метрики классификации: accuracy, precision, recall, F1",
            "Линейная регрессия",
            "Логистическая регрессия",
            "Дерево решений",
            "Random Forest",
            "Gradient Boosting (XGBoost / LightGBM)",
            "K-Means кластеризация",
            "Интерпретация моделей: feature importance, SHAP",
            "Сравнение и выбор модели",
            "Мини-проект: Прогноз оттока игроков",
        ],
    },
    {
        "number": 8,
        "title": "Feature Engineering",
        "description": "Создание признаков, кодирование, масштабирование, отбор. Тема — Видеоигры.",
        "theme": "gaming",
        "lessons_meta": [
            "Что такое feature engineering и почему это важно",
            "Создание новых признаков",
            "Кодирование категориальных переменных",
            "Масштабирование: MinMax, Standard, Robust",
            "Работа с датами: извлечение признаков",
            "Базовая обработка текста",
            "Отбор признаков: методы и метрики",
            "Мини-проект: Feature engineering для модели рекомендаций",
        ],
    },
    {
        "number": 9,
        "title": "Производственный Data Science",
        "description": "Git, Jupyter, структура ML-проекта, Docker, MLOps, воспроизводимость.",
        "theme": "neutral",
        "lessons_meta": [
            "Git: основы для Data Scientist",
            "Git: ветки, merge, pull request",
            "Jupyter Notebooks: best practices",
            "Структура ML-проекта",
            "Воспроизводимость: seeds, requirements.txt, README",
            "Docker: минимальный старт для DS",
            "Основы MLOps: эксперименты, версионирование",
            "Мини-проект: Оформить проект по стандартам GitHub",
        ],
    },
    {
        "number": 10,
        "title": "Подготовка к собеседованиям",
        "description": "280 вопросов по Python, SQL, статистике, ML, DS General. Junior-уровень.",
        "theme": "neutral",
        "lessons_meta": [],  # Вопросы хранятся в interview_questions
    },
]


# ============================================================================
# Проекты (20 штук)
# ============================================================================
PROJECTS: list[dict[str, Any]] = [
    # Игровые
    {
        "block": 3, "title": "G1: Анализ экономики игровой валюты",
        "description": "EDA + визуализация. Изучи распределение внутриигровой валюты среди игроков, выяви аномалии.",
        "theme": "gaming", "difficulty": 2,
    },
    {
        "block": 7, "title": "G2: Прогноз оттока игроков (Churn)",
        "description": "Логистическая регрессия. Предсказать, уйдёт ли игрок в ближайший месяц.",
        "theme": "gaming", "difficulty": 4,
    },
    {
        "block": 7, "title": "G3: Сегментация игроков по поведению",
        "description": "K-Means кластеризация. Выделить группы игроков по стилю игры.",
        "theme": "gaming", "difficulty": 3,
    },
    {
        "block": 5, "title": "G4: Балансировка оружия: анализ win rate",
        "description": "Статистические тесты. Определить, какое оружие нужно ослабить/усилить.",
        "theme": "gaming", "difficulty": 3,
    },
    {
        "block": 5, "title": "G5: A/B тест новой игровой механики",
        "description": "A/B тестирование. Проверить, улучшает ли новая механика retention.",
        "theme": "gaming", "difficulty": 4,
    },
    {
        "block": 8, "title": "G6: Рекомендательная система скинов",
        "description": "Feature Engineering. Построить рекомендации скинов на основе истории покупок.",
        "theme": "gaming", "difficulty": 4,
    },
    {
        "block": 5, "title": "G7: Анализ матчмейкинга и fairness",
        "description": "EDA + статистика. Проверить, насколько честно система подбирает соперников.",
        "theme": "gaming", "difficulty": 3,
    },
    {
        "block": 7, "title": "G8: Прогноз покупок Free-to-Play игроков",
        "description": "Random Forest. Предсказать, заплатит ли игрок в течение 30 дней.",
        "theme": "gaming", "difficulty": 4,
    },
    {
        "block": 7, "title": "G9: Обнаружение читеров по телеметрии",
        "description": "Anomaly Detection. Найти игроков с аномальным поведением.",
        "theme": "gaming", "difficulty": 5,
    },
    {
        "block": 2, "title": "G10: Дашборд retention и LTV",
        "description": "SQL + визуализация. Построить дашборд по основным метрикам.",
        "theme": "gaming", "difficulty": 3,
    },
    # Космические
    {
        "block": 3, "title": "S1: Анализ истории запусков SpaceX",
        "description": "EDA + визуализация. Изучить историю запусков, выявить тренды.",
        "theme": "space", "difficulty": 2,
    },
    {
        "block": 7, "title": "S2: Прогноз успеха посадки первой ступени",
        "description": "Логистическая регрессия. Предсказать, удастся ли посадить первую ступень.",
        "theme": "space", "difficulty": 4,
    },
    {
        "block": 4, "title": "S3: Анализ телеметрии спутника",
        "description": "EDA + статистика. Найти аномалии в данных телеметрии.",
        "theme": "space", "difficulty": 3,
    },
    {
        "block": 7, "title": "S4: Прогноз отказа двигателя",
        "description": "Random Forest. Предсказать отказ по телеметрии.",
        "theme": "space", "difficulty": 4,
    },
    {
        "block": 7, "title": "S5: Обнаружение аномалий в телеметрии",
        "description": "Isolation Forest. Выделить аномальные замеры.",
        "theme": "space", "difficulty": 4,
    },
    {
        "block": 7, "title": "S6: Классификация космических объектов",
        "description": "Decision Tree. Классифицировать типы объектов на орбите.",
        "theme": "space", "difficulty": 3,
    },
    {
        "block": 7, "title": "S7: Прогноз расхода топлива",
        "description": "Линейная регрессия. Предсказать расход топлива по параметрам полёта.",
        "theme": "space", "difficulty": 3,
    },
    {
        "block": 6, "title": "S8: Анализ данных марсохода Curiosity",
        "description": "EDA полный цикл. Исследовать данные с марсохода.",
        "theme": "space", "difficulty": 3,
    },
    {
        "block": 7, "title": "S9: Кластеризация экзопланет",
        "description": "K-Means + визуализация. Сгруппировать экзопланеты по характеристикам.",
        "theme": "space", "difficulty": 3,
    },
    {
        "block": 4, "title": "S10: Временной ряд: орбитальные данные",
        "description": "Trend analysis. Выявить тренды в орбитальных параметрах.",
        "theme": "space", "difficulty": 3,
    },
]


# ============================================================================
# Достижения (10 штук)
# ============================================================================
ACHIEVEMENTS: list[dict[str, Any]] = [
    {"key": "first_lesson", "title": "Первый шаг", "description": "Завершить первый урок", "icon": "🚀",
     "condition": {"type": "lessons_completed", "count": 1}},
    {"key": "python_master", "title": "Python-падаван", "description": "Завершить Блок 1", "icon": "🐍",
     "condition": {"type": "block_completed", "block": 1}},
    {"key": "sql_wizard", "title": "SQL-маг", "description": "Завершить Блок 2", "icon": "🔮",
     "condition": {"type": "block_completed", "block": 2}},
    {"key": "data_cleaner", "title": "Укротитель данных", "description": "Очистить 1000+ строк", "icon": "🧹",
     "condition": {"type": "rows_cleaned", "count": 1000}},
    {"key": "no_hints", "title": "Без подсказок", "description": "Решить 10 упражнений без подсказок", "icon": "🧠",
     "condition": {"type": "no_hint_solves", "count": 10}},
    {"key": "speed_run", "title": "Спидран", "description": "Решить упражнение за < 2 минут", "icon": "⚡",
     "condition": {"type": "fast_solve", "seconds": 120}},
    {"key": "perfect_score", "title": "Перфекционист", "description": "100% в любом блоке", "icon": "💯",
     "condition": {"type": "block_score", "percent": 100}},
    {"key": "half_way", "title": "Полпути", "description": "Завершить 50% курса", "icon": "🎯",
     "condition": {"type": "course_progress", "percent": 50}},
    {"key": "interview_ready", "title": "Готов к бою", "description": "Ответить на 50 вопросов собеседования", "icon": "💼",
     "condition": {"type": "interview_answered", "count": 50}},
    {"key": "graduate", "title": "Junior Data Scientist", "description": "Завершить все блоки", "icon": "🎓",
     "condition": {"type": "course_completed"}},
]


# ============================================================================
# Вопросы для собеседований (представительные 50, не 280)
# ============================================================================
INTERVIEW_QUESTIONS: list[dict[str, Any]] = [
    # Python
    {"category": "python", "question": "Чем отличается list от tuple?",
     "answer": "list — изменяемый (мутабельный), tuple — нет. Tuple быстрее, может быть ключом dict.",
     "explanation": "list использует [], tuple — (). list.append(), tuple не имеет мутирующих методов.",
     "common_mistakes": "Говорить 'tuple быстрее из-за immutable' — да, но точная разница ~10-20% на маленьких коллекциях.",
     "tags": ["types", "collections"], "is_top": True},
    {"category": "python", "question": "Что такое *args и **kwargs?",
     "answer": "*args — произвольное число позиционных аргументов (кортеж). **kwargs — именованных (словарь).",
     "explanation": "def f(*args, **kwargs): args=(1,2,3), kwargs={'a':1, 'b':2}",
     "common_mistakes": "Забыть распаковать: print(*args) вместо print(args).",
     "tags": ["functions"], "is_top": True},
    {"category": "python", "question": "Что такое list comprehension?",
     "answer": "Способ создать список в одну строку: [x**2 for x in range(10) if x % 2 == 0]",
     "explanation": "Быстрее цикла с append, читабельнее. Аналоги есть для dict, set.",
     "tags": ["syntax", "performance"], "is_top": True},
    {"category": "python", "question": "Чем `is` отличается от `==`?",
     "answer": "`is` сравнивает идентичность (один объект в памяти), `==` — равенство значений.",
     "explanation": "a = [1, 2]; b = [1, 2]; a == b (True), a is b (False). Для int/str кэширование может давать True для is.",
     "tags": ["operators"], "is_top": True},
    {"category": "python", "question": "Как работает словарь (dict) под капотом?",
     "answer": "Хеш-таблица: Python вычисляет hash(key), берёт остаток от деления на размер — это индекс корзины. Поиск O(1) в среднем.",
     "explanation": "Ключи должны быть hashable (иммутабельные). При коллизиях — открытая адресация.",
     "common_mistakes": "Путать сложность O(1) среднюю и худшую (O(n) при коллизиях).",
     "tags": ["data-structures", "hash"], "is_top": True},
    {"category": "python", "question": "Что такое генератор (generator)?",
     "answer": "Функция с yield, возвращающая итератор. Ленивая — не хранит все значения в памяти.",
     "explanation": "def gen(): yield 1; yield 2. range() — генератор.",
     "tags": ["iterators"], "is_top": True},
    {"category": "python", "question": "Что делает `with` при работе с файлами?",
     "answer": "Гарантирует вызов .close() даже при исключении. Реализация context manager (методы __enter__/__exit__).",
     "explanation": "with open() as f: ... — эквивалент try-finally с f.close().",
     "tags": ["files", "context-manager"], "is_top": True},
    {"category": "python", "question": "Чем `__init__` отличается от `__new__`?",
     "answer": "__new__ создаёт экземпляр (вызывается первым), __init__ инициализирует его.",
     "explanation": "Для иммутабельных типов (tuple, str) модификации делают через __new__.",
     "tags": ["oop"], "is_top": False},
    {"category": "python", "question": "Что такое GIL?",
     "answer": "Global Interpreter Lock — блокировка, позволяющая только одному потоку Python выполнять байт-код одновременно.",
     "explanation": "Для CPU-bound задач — multiprocessing, не threading. Для I/O — threading ОК.",
     "common_mistakes": "Думать, что threading бесполезен. Для I/O (requests, файлы) он эффективен.",
     "tags": ["concurrency"], "is_top": True},
    {"category": "python", "question": "Что такое lambda-функция?",
     "answer": "Анонимная функция в одну строку: lambda x: x**2",
     "explanation": "Ограничение: только выражение, нельзя присваивать. Для сложного — def.",
     "tags": ["functions"], "is_top": True},
    {"category": "python", "question": "Чем set отличается от list?",
     "answer": "set — неупорядоченный, уникальные элементы, операции | & -. list — упорядоченный, с дубликатами.",
     "explanation": "set быстрее для проверки 'есть ли элемент' (O(1) vs O(n)).",
     "tags": ["collections"], "is_top": True},
    {"category": "python", "question": "Что такое декоратор?",
     "answer": "Функция, оборачивающая другую функцию для добавления поведения.",
     "explanation": "@decorator — синтаксический сахар. Декоратор принимает функцию и возвращает функцию.",
     "tags": ["functions", "metaprogramming"], "is_top": True},
    # SQL
    {"category": "sql", "question": "В чём разница между WHERE и HAVING?",
     "answer": "WHERE фильтрует строки ДО GROUP BY. HAVING фильтрует группы ПОСЛЕ.",
     "explanation": "WHERE нельзя использовать с агрегатами (в строгом SQL).",
     "tags": ["filtering"], "is_top": True},
    {"category": "sql", "question": "Что вернёт запрос SELECT COUNT(*) FROM empty_table?",
     "answer": "0. COUNT(*) считает строки, даже с NULL.",
     "explanation": "COUNT(col) — только NOT NULL значения.",
     "tags": ["aggregates"], "is_top": True},
    {"category": "sql", "question": "В чём разница между INNER JOIN и LEFT JOIN?",
     "answer": "INNER — только совпадающие строки. LEFT — все из левой + NULL для несовпавших.",
     "explanation": "RIGHT — зеркало LEFT. FULL OUTER — все из обеих.",
     "tags": ["joins"], "is_top": True},
    {"category": "sql", "question": "Что такое оконная функция?",
     "answer": "Функция, которая считает по 'окну' строк, не схлопывая результат: ROW_NUMBER(), SUM() OVER, RANK().",
     "explanation": "PARTITION BY — аналог GROUP BY, но без схлопывания.",
     "tags": ["window-functions"], "is_top": True},
    {"category": "sql", "question": "Чем UNION отличается от UNION ALL?",
     "answer": "UNION убирает дубликаты, UNION ALL — оставляет. UNION ALL быстрее.",
     "explanation": "UNION требует сортировки для дедупликации.",
     "tags": ["set-operations"], "is_top": True},
    {"category": "sql", "question": "Что такое CTE?",
     "answer": "Common Table Expression — именованный подзапрос через WITH.",
     "explanation": "WITH name AS (SELECT ...) SELECT ... — читабельнее подзапроса.",
     "tags": ["cte"], "is_top": True},
    {"category": "sql", "question": "Что такое индекс? Зачем он нужен?",
     "answer": "Структура для быстрого поиска (оглавление). Ускоряет SELECT, замедляет INSERT/UPDATE.",
     "explanation": "B-tree — для диапазонов. Hash — для =. Композитный — несколько столбцов.",
     "tags": ["performance", "indexes"], "is_top": True},
    {"category": "sql", "question": "Что такое нормализация?",
     "answer": "Процесс организации данных для уменьшения избыточности (1NF, 2NF, 3NF, BCNF).",
     "explanation": "1NF: атомарные значения. 2NF: 1NF + нет частичных зависимостей. 3NF: 2NF + нет транзитивных.",
     "tags": ["design"], "is_top": True},
    {"category": "sql", "question": "ROW_NUMBER vs RANK vs DENSE_RANK?",
     "answer": "ROW_NUMBER: 1,2,3,4. RANK: 1,1,3,4 (с пропусками). DENSE_RANK: 1,1,2,3 (без пропусков).",
     "explanation": "Все — оконные функции с ORDER BY.",
     "tags": ["window-functions"], "is_top": True},
    # Статистика
    {"category": "statistics", "question": "Что такое p-value?",
     "answer": "Вероятность получить наблюдаемый результат (или более экстремальный) при условии, что нулевая гипотеза верна.",
     "explanation": "p < 0.05 — обычно отвергаем H0. p-value ≠ вероятность H0.",
     "common_mistakes": "Говорить 'p-value — вероятность H0'. Это неверно.",
     "tags": ["hypothesis-testing"], "is_top": True},
    {"category": "statistics", "question": "Чем среднее отличается от медианы?",
     "answer": "Среднее = сумма / кол-во (чувствительно к выбросам). Медиана = середина отсортированного массива (устойчива).",
     "explanation": "Для асимметричных распределений (доходы) медиана репрезентативнее.",
     "tags": ["descriptive"], "is_top": True},
    {"category": "statistics", "question": "Что такое корреляция?",
     "answer": "Мера линейной связи от -1 до +1. 0 = нет линейной связи, но нелинейная может быть.",
     "explanation": "Корреляция ≠ причинно-следственная связь. Спатиальная корреляция — пример ложной.",
     "common_mistakes": "Говорить 'корреляция = причинность'.",
     "tags": ["correlation"], "is_top": True},
    {"category": "statistics", "question": "Что такое центральная предельная теорема?",
     "answer": "Распределение среднего по выборкам сходится к нормальному при росте n, независимо от исходного распределения.",
     "explanation": "Обосновывает использование нормального распределения в статистике.",
     "tags": ["distributions"], "is_top": True},
    {"category": "statistics", "question": "Что такое доверительный интервал?",
     "answer": "Диапазон, в который с заданной вероятностью (обычно 95%) попадает истинное значение параметра.",
     "explanation": "95% ДИ для среднего: x ± 1.96 * SE.",
     "tags": ["estimation"], "is_top": True},
    {"category": "statistics", "question": "Что такое A/B тест?",
     "answer": "Эксперимент: делим пользователей на 2 группы (контроль и тест), сравниваем метрику.",
     "explanation": "Нужна достаточная выборка, рандомизация, одна изменённая переменная.",
     "tags": ["ab-testing"], "is_top": True},
    # ML
    {"category": "ml", "question": "Что такое переобучение (overfitting)?",
     "answer": "Модель хорошо работает на train, плохо на test. Запомнила шум, а не закономерности.",
     "explanation": "Признаки: train accuracy 99%, test 60%. Решения: больше данных, регуляризация, проще модель.",
     "tags": ["bias-variance"], "is_top": True},
    {"category": "ml", "question": "Чем supervised отличается от unsupervised?",
     "answer": "Supervised — есть метки (X, y). Unsupervised — только X, ищем структуру.",
     "explanation": "Supervised: классификация, регрессия. Unsupervised: кластеризация, понижение размерности.",
     "tags": ["basics"], "is_top": True},
    {"category": "ml", "question": "Что такое precision и recall?",
     "answer": "Precision = TP / (TP + FP) — точность. Recall = TP / (TP + FN) — полнота.",
     "explanation": "F1 = 2 * P * R / (P + R). Для дисбаланса классов — смотреть и то, и другое.",
     "common_mistakes": "Использовать accuracy при дисбалансе (90% класс 0 → 90% accuracy на константе).",
     "tags": ["metrics"], "is_top": True},
    {"category": "ml", "question": "Зачем нужна кросс-валидация?",
     "answer": "Чтобы оценить качество модели на новых данных. Разбиваем на k фолдов, обучаем k раз.",
     "explanation": "5-fold CV: train на 4, test на 1, повторяем 5 раз. Среднее — оценка.",
     "tags": ["validation"], "is_top": True},
    {"category": "ml", "question": "Что такое Random Forest?",
     "answer": "Ансамбль деревьев решений. Каждое дерево — на случайной подвыборке данных и признаков.",
     "explanation": "Бэггинг + случайные подпространства. Устойчив к переобучению.",
     "tags": ["ensembles"], "is_top": True},
    {"category": "ml", "question": "Что такое регуляризация?",
     "answer": "Добавление штрафа за сложность модели: L1 (Lasso) или L2 (Ridge).",
     "explanation": "L1 зануляет коэффициенты (отбор признаков). L2 уменьшает их.",
     "tags": ["regularization"], "is_top": True},
    {"category": "ml", "question": "Что такое feature engineering?",
     "answer": "Создание новых признаков из сырых данных: логарифмы, полиномы, агрегации, кодирование.",
     "explanation": "Хороший feature >> хороший алгоритм. 80% успеха в DS — это фичи.",
     "tags": ["features"], "is_top": True},
    {"category": "ml", "question": "Что такое градиентный спуск?",
     "answer": "Оптимизационный метод: обновляем параметры в направлении антиградиента loss.",
     "explanation": "lr — learning rate. SGD, Adam, RMSprop — вариации.",
     "tags": ["optimization"], "is_top": True},
    {"category": "ml", "question": "Что такое K-Means?",
     "answer": "Алгоритм кластеризации: K центроидов, итеративно пересчитываем.",
     "explanation": "Нужно задать K. Чувствителен к инициализации и выбросам.",
     "tags": ["clustering"], "is_top": True},
    {"category": "ml", "question": "Зачем нужен train/test split?",
     "answer": "Чтобы оценить качество на новых данных. Train для обучения, test — для оценки.",
     "explanation": "Обычно 80/20. Стратификация для дисбаланса. Временной ряд — не перемешивать!",
     "tags": ["validation"], "is_top": True},
    {"category": "ml", "question": "Что такое logistic regression?",
     "answer": "Классификация через сигмоиду: P(y=1|X) = 1 / (1 + exp(-X*w)). Несмотря на 'regression' — это классификация.",
     "explanation": "Линейная модель для бинарной классификации. Можно расширить на мультикласс.",
     "tags": ["classification"], "is_top": True},
    # DS General
    {"category": "ds_general", "question": "Опишите полный цикл Data Science проекта.",
     "answer": "1) Бизнес-задача → 2) Данные → 3) Очистка → 4) EDA → 5) Feature Engineering → 6) Моделирование → 7) Оценка → 8) Визуализация → 9) Деплой.",
     "explanation": "Это не линейный процесс — часто возвращаемся назад.",
     "tags": ["process"], "is_top": True},
    {"category": "ds_general", "question": "Как бороться с пропусками в данных?",
     "answer": "Удалить строки, заполнить средним/медианой/модой, предсказать моделью, создать флаг 'был пропуск'.",
     "explanation": "Стратегия зависит от причины пропуска (MCAR, MAR, MNAR).",
     "tags": ["preprocessing"], "is_top": True},
    {"category": "ds_general", "question": "Что такое Data Leakage?",
     "answer": "Утечка данных: использование информации из test в train. Модель выглядит отлично, но в проде проваливается.",
     "explanation": "Примеры: scaling до split, target в features, временной leak.",
     "common_mistakes": "Забыть про временной порядок при time series.",
     "tags": ["pitfalls"], "is_top": True},
    {"category": "ds_general", "question": "Что такое ROC-AUC?",
     "answer": "Площадь под ROC-кривой. 1.0 = идеально, 0.5 = случайно. Устойчив к дисбалансу.",
     "explanation": "ROC = TPR vs FPR. AUC = вероятность, что случайный positive > случайного negative.",
     "tags": ["metrics"], "is_top": True},
    {"category": "ds_general", "question": "Как оценить важность признаков?",
     "answer": "Корреляция, feature importance из деревьев, permutation importance, SHAP.",
     "explanation": "SHAP — state-of-the-art, локальная и глобальная интерпретация.",
     "tags": ["interpretation"], "is_top": True},
    {"category": "ds_general", "question": "Что такое bias-variance tradeoff?",
     "answer": "Bias — ошибка от упрощения, variance — от чувствительности к данным. Нужно балансировать.",
     "explanation": "Простая модель: high bias, low variance. Сложная: low bias, high variance.",
     "tags": ["theory"], "is_top": True},
    {"category": "ds_general", "question": "Как выбрать метрику для задачи?",
     "answer": "Зависит от бизнес-задачи. Классификация: accuracy / F1 / AUC. Регрессия: MAE / RMSE / R².",
     "explanation": "При дисбалансе — F1, AUC. При выбросах в регрессии — MAE, не RMSE.",
     "tags": ["metrics"], "is_top": True},
    {"category": "ds_general", "question": "Что такое exploratory data analysis (EDA)?",
     "answer": "Исследование данных перед моделированием: распределения, выбросы, пропуски, корреляции, визуализация.",
     "explanation": "Цель — понять данные, выдвинуть гипотезы, найти аномалии.",
     "tags": ["eda"], "is_top": True},
    {"category": "ds_general", "question": "Что такое нормализация и зачем она нужна?",
     "answer": "Приведение признаков к одной шкале (MinMax 0..1 или Standard mean=0, std=1). Нужно для KNN, SVM, нейросетей, PCA.",
     "explanation": "Для деревьев — не нужно. Всегда fit на train, transform на train+test.",
     "common_mistakes": "Fit нормализатор на всём датасете, потом делить — leak.",
     "tags": ["preprocessing"], "is_top": True},
    {"category": "ds_general", "question": "Что такое dimensionality reduction?",
     "answer": "Уменьшение числа признаков с сохранением информации. PCA, t-SNE, UMAP.",
     "explanation": "PCA — линейный, t-SNE/UMAP — для визуализации. Используют для feature engineering и визуализации.",
     "tags": ["preprocessing"], "is_top": True},
]
