"""
Дополнительные SQL-упражнения для Блока 2.
Доводит количество упражнений до ~10 на урок.
Охватывает пропущенные темы: LIKE, COALESCE, EXISTS, UNION, DDL, строковые функции.
"""
from app.seed_helpers import ex


# ============================================================================
# 2.1 — SELECT, FROM, WHERE (8 → 10)
# ============================================================================
EX_2_1 = [
    ex(9, "sql", "Выбрать игроков, у которых team_id равен 1 или 3. Используй IN.",
       "SELECT * FROM players WHERE team_id IN (?);\n",
       "SELECT * FROM players WHERE team_id IN (1, 3);",
       [{"check": "len(result) == 3", "msg": "Alice (1), Bob (1), Eve (3)"}],
       ["IN (1, 3) — список значений"], 1),
    ex(10, "sql", "Выбрать игроков, чьё имя начинается на букву 'A' или 'B'. Используй LIKE.",
       "SELECT * FROM players WHERE name LIKE ?;\n",
       "SELECT * FROM players WHERE name LIKE 'A%' OR name LIKE 'B%';",
       [{"check": "len(result) == 2", "msg": "Alice и Bob"}],
       ["LIKE 'A%' — начинается с A", "OR для нескольких условий"], 2),
]

# ============================================================================
# 2.2 — ORDER BY, LIMIT, DISTINCT (7 → 10)
# ============================================================================
EX_2_2 = [
    ex(8, "sql", "Пропустить первого игрока и показать следующих двух по убыванию score. Используй LIMIT с OFFSET.",
       "SELECT * FROM players ORDER BY score ? LIMIT ? OFFSET ?;\n",
       "SELECT * FROM players ORDER BY score DESC LIMIT 2 OFFSET 1;",
       [{"check": "len(result) == 2 and result[0]['name'] != 'Alice'", "msg": "Diana (1200) и Eve (950)"}],
       ["LIMIT 2 OFFSET 1 — пропустить 1 строку"], 2),
    ex(9, "sql", "Выбрать уникальные team_id из таблицы players с помощью DISTINCT.",
       "SELECT ? team_id FROM players;\n",
       "SELECT DISTINCT team_id FROM players;",
       [{"check": "len(result) == 3", "msg": "Значения 1, 2, 3"}],
       ["DISTINCT убирает дубликаты"], 1),
    ex(10, "sql", "Выбрать имена и удвоенный score. Отсортировать по убыванию удвоенного score.",
       "SELECT name, score * ? AS double_score FROM players ORDER BY ? DESC;\n",
       "SELECT name, score * 2 AS double_score FROM players ORDER BY double_score DESC;",
       [{"check": "len(result) == 5 and result[0]['double_score'] == 3000", "msg": "Alice — 3000 (1500*2)"}],
       ["Можно сортировать по псевдониму (alias)"], 2),
]

# ============================================================================
# 2.3 — Агрегаты (7 → 10)
# ============================================================================
EX_2_3 = [
    ex(8, "sql", "Посчитать количество уникальных team_id среди игроков. Используй COUNT с DISTINCT.",
       "SELECT COUNT(DISTINCT ?) FROM players;\n",
       "SELECT COUNT(DISTINCT team_id) FROM players;",
       [{"check": "result[0]['COUNT(DISTINCT team_id)'] == 3", "msg": "Три разные команды"}],
       ["COUNT(DISTINCT col) — без дублей"], 2),
    ex(9, "sql", "Найти сумму всех score и средний score одновременно. Дай псевдонимы.",
       "SELECT SUM(score) AS total_score, ?(score) AS avg_score FROM players;\n",
       "SELECT SUM(score) AS total_score, AVG(score) AS avg_score FROM players;",
       [{"check": "result[0]['total_score'] == 5050", "msg": "5050 — сумма всех score"}],
       ["Несколько агрегатов в одном SELECT"], 2),
    ex(10, "sql", "Посчитать количество игроков, у которых score выше среднего. Используй подзапрос.",
       "SELECT COUNT(*) FROM players WHERE score > (SELECT ?(score) FROM players);\n",
       "SELECT COUNT(*) FROM players WHERE score > (SELECT AVG(score) FROM players);",
       [{"check": "result[0]['COUNT(*)'] >= 1", "msg": "Игроки выше среднего"}],
       ["Подзапрос в WHERE"], 3),
]

# ============================================================================
# 2.4 — GROUP BY и HAVING (5 → 10)
# ============================================================================
EX_2_4 = [
    ex(6, "sql", "Посчитать количество игроков в каждой команде (team_id). Отсортировать по убыванию.",
       "SELECT team_id, COUNT(*) AS cnt FROM players GROUP BY ? ORDER BY cnt ?;\n",
       "SELECT team_id, COUNT(*) AS cnt FROM players GROUP BY team_id ORDER BY cnt DESC;",
       [{"check": "result[0]['team_id'] == 1", "msg": "В team_id=1 два игрока"}],
       ["GROUP BY + ORDER BY"], 1),
    ex(7, "sql", "Выбрать team_id, где максимальный score превышает 1000.",
       "SELECT team_id, MAX(score) AS max_score FROM players GROUP BY team_id HAVING max_score ? 1000;\n",
       "SELECT team_id, MAX(score) AS max_score FROM players GROUP BY team_id HAVING max_score > 1000;",
       [{"check": "len(result) == 2", "msg": "team_id=1 (Alice 1500) и team_id=2 (Diana 1200)"}],
       ["HAVING фильтрует после GROUP BY"], 2),
    ex(8, "sql", "Посчитать сумму score для каждой команды. Исключить team_id = NULL.",
       "SELECT team_id, SUM(score) AS total FROM players WHERE team_id IS NOT ? GROUP BY team_id;\n",
       "SELECT team_id, SUM(score) AS total FROM players WHERE team_id IS NOT NULL GROUP BY team_id;",
       [{"check": "len(result) == 3", "msg": "Суммы для трёх команд"}],
       ["IS NOT NULL — исключить пропуски"], 2),
    ex(9, "sql", "Выбрать team_id, где средний score > 800 и количество игроков > 1.",
       "SELECT team_id, AVG(score) AS avg_s, COUNT(*) AS cnt FROM players GROUP BY team_id HAVING avg_s ? 800 AND cnt ? 1;\n",
       "SELECT team_id, AVG(score) AS avg_s, COUNT(*) AS cnt FROM players GROUP BY team_id HAVING avg_s > 800 AND cnt > 1;",
       [{"check": "len(result) == 1", "msg": "Только team_id=1 (avg 1150, 2 игрока)"}],
       ["Несколько условий в HAVING через AND"], 3),
    ex(10, "sql", "Выбрать team_id и разницу между MAX и MIN score. Назвать столбец score_range.",
       "SELECT team_id, ?(score) - ?(score) AS score_range FROM players GROUP BY team_id;\n",
       "SELECT team_id, MAX(score) - MIN(score) AS score_range FROM players GROUP BY team_id;",
       [{"check": "result[0]['team_id'] == 1 and result[0]['score_range'] == 700", "msg": "Для team_id=1: 1500-800=700"}],
       ["Агрегаты в выражениях"], 2),
]

# ============================================================================
# 2.5 — CASE WHEN (3 → 10)
# ============================================================================
EX_2_5 = [
    ex(4, "sql", "Вывести name и team_id. Если team_id = 1 — 'Red', 2 — 'Blue', иначе 'Other'. Назвать столбец team_color.",
       "SELECT name, CASE team_id WHEN 1 THEN 'Red' WHEN ? THEN 'Blue' ELSE ? END AS team_color FROM players;\n",
       "SELECT name, CASE team_id WHEN 1 THEN 'Red' WHEN 2 THEN 'Blue' ELSE 'Other' END AS team_color FROM players;",
       [{"check": "len(result) == 5", "msg": "Alice/Bob — Red, Charlie/Diana — Blue, Eve — Other"}],
       ["CASE с WHEN после значения столбца"], 2),
    ex(5, "sql", "Вывести name и status: если score > 1000 — 'high', если > 700 — 'mid', иначе 'low'.",
       "SELECT name, CASE WHEN score > 1000 THEN 'high' WHEN score > ? THEN 'mid' ELSE ? END AS status FROM players;\n",
       "SELECT name, CASE WHEN score > 1000 THEN 'high' WHEN score > 700 THEN 'mid' ELSE 'low' END AS status FROM players;",
       [{"check": "result[0]['status'] == 'high'", "msg": "Alice (1500) и Diana (1200) — high"}],
       ["CASE WHEN с условиями"], 2),
    ex(6, "sql", "Для каждого игрока вывести name и is_premium: если score > 1000 — 'yes', иначе 'no'.",
       "SELECT name, CASE WHEN score > 1000 THEN ? ELSE ? END AS is_premium FROM players;\n",
       "SELECT name, CASE WHEN score > 1000 THEN 'yes' ELSE 'no' END AS is_premium FROM players;",
       [{"check": "result[0]['is_premium'] == 'yes'", "msg": "Alice — yes (1500)"}],
       ["THEN и ELSE со строками"], 1),
    ex(7, "sql", "Посчитать количество игроков в каждой категории score. Категории: 'high' (>1000), 'mid' (500-1000), 'low' (<500).",
       "SELECT CASE WHEN score > 1000 THEN 'high' WHEN score >= 500 THEN 'mid' ELSE 'low' END AS category, COUNT(*) AS cnt FROM players GROUP BY category;\n",
       "SELECT CASE WHEN score > 1000 THEN 'high' WHEN score >= 500 THEN 'mid' ELSE 'low' END AS category, COUNT(*) AS cnt FROM players GROUP BY category;",
       [{"check": "len(result) == 2", "msg": "2 high (Alice, Diana), 3 mid (Bob, Charlie, Eve)"}],
       ["CASE + GROUP BY — мощная комбинация"], 3),
    ex(8, "sql", "Вывести name и score. Если team_id = 1, показать 'Team A', иначе 'Other'. Объединить CASE с ORDER BY.",
       "SELECT name, CASE WHEN team_id = 1 THEN 'Team A' ? 'Other' END AS team_group FROM players ORDER BY name;\n",
       "SELECT name, CASE WHEN team_id = 1 THEN 'Team A' ELSE 'Other' END AS team_group FROM players ORDER BY name;",
       [{"check": "result[0]['team_group'] == 'Team A'", "msg": "Alice отсортирована первой"}],
       ["CASE в SELECT + ORDER BY"], 2),
    ex(9, "sql", "Заменить NULL в team_id на 0 с помощью COALESCE. Вывести name и team_id или 'No team'.",
       "SELECT name, COALESCE(?, 0) AS team_id_fixed FROM players;\n",
       "SELECT name, COALESCE(team_id, 0) AS team_id_fixed FROM players;",
       [{"check": "all(r['team_id_fixed'] in (0,1,2,3) for r in result)", "msg": "Все team_id без NULL"}],
       ["COALESCE — замена NULL"], 2),
    ex(10, "sql", "Вывести name и score. Добавить столбец score_bonus: если score > 1000, добавить 100, иначе 0.",
       "SELECT name, score, CASE WHEN score > 1000 THEN score + ? ELSE score END AS score_bonus FROM players;\n",
       "SELECT name, score, CASE WHEN score > 1000 THEN score + 100 ELSE score END AS score_bonus FROM players;",
       [{"check": "result[0]['score_bonus'] == 1600", "msg": "Alice: 1500 + 100 = 1600"}],
       ["CASE в выражении"], 2),
]

# ============================================================================
# 2.6 — INNER JOIN, LEFT JOIN (3 → 10)
# ============================================================================
EX_2_6 = [
    ex(4, "sql", "Через INNER JOIN вывести имя игрока и название его команды.",
       "SELECT p.name, t.team_name FROM players p INNER JOIN teams t ON p.team_id = t.id;\n",
       "SELECT p.name, t.team_name FROM players p INNER JOIN teams t ON p.team_id = t.id;",
       [{"check": "len(result) == 5", "msg": "Все 5 игроков со своими командами"}],
       ["INNER JOIN — только совпадающие"], 1),
    ex(5, "sql", "Вывести имя игрока и название команды. Если у игрока нет команды, имя команды показать как NULL. Используй LEFT JOIN.",
       "SELECT p.name, t.team_name FROM players p LEFT JOIN teams t ON p.team_id = t.id;\n",
       "SELECT p.name, t.team_name FROM players p LEFT JOIN teams t ON p.team_id = t.id;",
       [{"check": "len(result) == 5", "msg": "Всегда LEFT JOIN >= INNER JOIN по строкам"}],
       ["LEFT JOIN — все строки из левой таблицы"], 2),
    ex(6, "sql", "Вывести команды, в которых есть игроки (без повторов). Используй JOIN + DISTINCT.",
       "SELECT DISTINCT t.team_name FROM players p JOIN teams t ON p.team_id = t.id;\n",
       "SELECT DISTINCT t.team_name FROM players p JOIN teams t ON p.team_id = t.id;",
       [{"check": "len(result) == 3", "msg": "Red, Blue, Green"}],
       ["DISTINCT + JOIN"], 1),
    ex(7, "sql", "Вывести пары игроков из одной команды. Используй self-JOIN (псевдонимы p1, p2).",
       "SELECT p1.name AS player1, p2.name AS player2 FROM players p1 JOIN players p2 ON p1.team_id = p2.team_id WHERE p1.name < p2.name;\n",
       "SELECT p1.name AS player1, p2.name AS player2 FROM players p1 JOIN players p2 ON p1.team_id = p2.team_id WHERE p1.name < p2.name;",
       [{"check": "len(result) == 1", "msg": "Alice и Bob в одной команде (team_id=1)"}],
       ["Self-JOIN — таблица сама с собой"], 3),
    ex(8, "sql", "Посчитать количество игроков в каждой команде через JOIN. Вывести team_name и cnt.",
       "SELECT t.team_name, COUNT(p.id) AS cnt FROM teams t LEFT JOIN players p ON t.id = p.team_id GROUP BY t.team_name;\n",
       "SELECT t.team_name, COUNT(p.id) AS cnt FROM teams t LEFT JOIN players p ON t.id = p.team_id GROUP BY t.team_name;",
       [{"check": "len(result) == 3", "msg": "Red: 2, Blue: 2, Green: 1"}],
       ["LEFT JOIN + GROUP BY — включает команды без игроков"], 2),
    ex(9, "sql", "Найти средний score игроков для каждой команды через JOIN. Вывести team_name и avg_score.",
       "SELECT t.team_name, AVG(p.score) AS avg_score FROM teams t JOIN players p ON t.id = p.team_id GROUP BY t.team_name;\n",
       "SELECT t.team_name, AVG(p.score) AS avg_score FROM teams t JOIN players p ON t.id = p.team_id GROUP BY t.team_name;",
       [{"check": "result[0]['team_name'] == 'Red' and result[0]['avg_score'] == 1150.0", "msg": "Red: avg=1150"}],
       ["JOIN + GROUP BY + AVG"], 2),
    ex(10, "sql", "Вывести игроков, у которых team_id совпадает с id = 2 в teams. Используй JOIN с WHERE.",
       "SELECT p.name, p.score FROM players p JOIN teams t ON p.team_id = t.id WHERE t.team_name = 'Blue';\n",
       "SELECT p.name, p.score FROM players p JOIN teams t ON p.team_id = t.id WHERE t.team_name = 'Blue';",
       [{"check": "len(result) == 2", "msg": "Charlie и Diana — команда Blue"}],
       ["JOIN + WHERE — фильтр после объединения"], 2),
]

# ============================================================================
# 2.7 — RIGHT JOIN, FULL JOIN, CROSS JOIN (2 → 10)
# ============================================================================
EX_2_7 = [
    ex(3, "sql", "Через LEFT JOIN показать все команды и их игроков. Найти команды без игроков (где p.id IS NULL).",
       "SELECT t.team_name, p.name FROM teams t LEFT JOIN players p ON t.id = p.team_id;\n",
       "SELECT t.team_name, p.name FROM teams t LEFT JOIN players p ON t.id = p.team_id;",
       [{"check": "len(result) == 5", "msg": "Все 3 команды, игроки где есть"}],
       ["LEFT JOIN команд → игроков эмулирует RIGHT JOIN"], 2),
    ex(4, "sql", "CROSS JOIN — декартово произведение игроков и команд. Сколько строк получится?",
       "SELECT p.name, t.team_name FROM players p CROSS JOIN teams t;\n",
       "SELECT p.name, t.team_name FROM players p CROSS JOIN teams t;",
       [{"check": "len(result) == 15", "msg": "5 игроков × 3 команды = 15 строк"}],
       ["CROSS JOIN = все комбинации (5 × 3 = 15)"], 2),
    ex(5, "sql", "Объединить две таблицы через UNION ALL: список id из players и id из teams в один столбец.",
       "SELECT id AS entity_id FROM players UNION ALL SELECT id FROM teams;\n",
       "SELECT id AS entity_id FROM players UNION ALL SELECT id FROM teams;",
       [{"check": "len(result) == 8", "msg": "5 players + 3 teams = 8 строк"}],
       ["UNION ALL — все строки из обоих запросов"], 2),
    ex(6, "sql", "Создать комбинации team_name и score через CROSS JOIN, где score > 1000.",
       "SELECT t.team_name, p.score FROM teams t CROSS JOIN players p WHERE p.score > 1000;\n",
       "SELECT t.team_name, p.score FROM teams t CROSS JOIN players p WHERE p.score > 1000;",
       [{"check": "len(result) == 6", "msg": "3 команды × 2 игрока с score > 1000 = 6"}],
       ["CROSS JOIN + WHERE — фильтр после декартова произведения"], 2),
    ex(7, "sql", "Через LEFT JOIN показать team_name и количество игроков. Вывести и команды без игроков (cnt = 0).",
       "SELECT t.team_name, COUNT(p.id) AS cnt FROM teams t LEFT JOIN players p ON t.id = p.team_id GROUP BY t.team_name;\n",
       "SELECT t.team_name, COUNT(p.id) AS cnt FROM teams t LEFT JOIN players p ON t.id = p.team_id GROUP BY t.team_name;",
       [{"check": "result[2]['cnt'] == 1", "msg": "Green — 1 игрок (Eve)"}],
       ["LEFT JOIN + COUNT — включает 0"], 2),
    ex(8, "sql", "Вывести имя игрока и название команды. Для игроков без команды показать 'No team' через COALESCE.",
       "SELECT p.name, COALESCE(t.team_name, 'No team') AS team FROM players p LEFT JOIN teams t ON p.team_id = t.id;\n",
       "SELECT p.name, COALESCE(t.team_name, 'No team') AS team FROM players p LEFT JOIN teams t ON p.team_id = t.id;",
       [{"check": "len(result) == 5", "msg": "COALESCE заменяет NULL на 'No team'"}],
       ["LEFT JOIN + COALESCE — безопасное отображение"], 3),
    ex(9, "sql", "Создать все возможные пары одинаковых team_id через self-JOIN с WHERE p1.id < p2.id.",
       "SELECT p1.name AS n1, p2.name AS n2 FROM players p1 JOIN players p2 ON p1.team_id = p2.team_id AND p1.id < p2.id;\n",
       "SELECT p1.name AS n1, p2.name AS n2 FROM players p1 JOIN players p2 ON p1.team_id = p2.team_id AND p1.id < p2.id;",
       [{"check": "len(result) == 1", "msg": "Только Alice и Bob (team_id=1)"}],
       ["Self-JOIN с условием p1.id < p2.id — избегает дубликатов"], 3),
    ex(10, "sql", "Через LEFT JOIN найти команды, в которых нет игроков. Подсказка: WHERE p.id IS NULL.",
       "SELECT t.team_name FROM teams t LEFT JOIN players p ON t.id = p.team_id WHERE p.id IS NULL;\n",
       "SELECT t.team_name FROM teams t LEFT JOIN players p ON t.id = p.team_id WHERE p.id IS NULL;",
       [{"check": "len(result) == 0", "msg": "Нет команд без игроков (все имеют хотя бы одного)"}],
       ["LEFT JOIN + WHERE ... IS NULL — поиск отсутствующих"], 3),
]

# ============================================================================
# 2.8 — Подзапросы (3 → 10)
# ============================================================================
EX_2_8 = [
    ex(4, "sql", "Через EXISTS найти игроков, которые состоят в команде (team_id существует в teams).",
       "SELECT name FROM players p WHERE EXISTS (SELECT 1 FROM teams t WHERE t.id = p.team_id);\n",
       "SELECT name FROM players p WHERE EXISTS (SELECT 1 FROM teams t WHERE t.id = p.team_id);",
       [{"check": "len(result) == 5", "msg": "Все 5 игроков в командах"}],
       ["EXISTS — проверяет наличие подстроки"], 2),
    ex(5, "sql", "Через IN найти игроков, чей team_id есть в teams (т.е. в (1, 2, 3)).",
       "SELECT name FROM players WHERE team_id IN (SELECT id FROM teams);\n",
       "SELECT name FROM players WHERE team_id IN (SELECT id FROM teams);",
       [{"check": "len(result) == 5", "msg": "Все 5 игроков"}],
       ["IN (SELECT ...) — подзапрос в списке"], 2),
    ex(6, "sql", "Вывести имена игроков и их score в процентах от максимального score. Используй подзапрос в SELECT.",
       "SELECT name, ROUND(score * 100.0 / (SELECT MAX(score) FROM players), 1) AS pct FROM players;\n",
       "SELECT name, ROUND(score * 100.0 / (SELECT MAX(score) FROM players), 1) AS pct FROM players;",
       [{"check": "result[0]['pct'] == 100.0", "msg": "Alice — 100% (максимальный score)"}],
       ["Подзапрос в SELECT — скалярное значение"], 3),
    ex(7, "sql", "Через подзапрос в FROM найти команды со средним score > 900. Подзапрос считает avg_score по team_id.",
       "SELECT * FROM (SELECT team_id, AVG(score) AS avg_score FROM players GROUP BY team_id) AS sq WHERE avg_score > 900;\n",
       "SELECT * FROM (SELECT team_id, AVG(score) AS avg_score FROM players GROUP BY team_id) AS sq WHERE avg_score > 900;",
       [{"check": "len(result) == 1", "msg": "Только team_id=1 (avg 1150)"}],
       ["Подзапрос в FROM — производная таблица"], 3),
    ex(8, "sql", "Найти игроков, у которых score выше, чем у любого игрока из team_id = 2.",
       "SELECT name, score FROM players WHERE score > ALL (SELECT score FROM players WHERE team_id = 2);\n",
       "SELECT name, score FROM players WHERE score > ALL (SELECT score FROM players WHERE team_id = 2);",
       [{"check": "len(result) == 1 and result[0]['name'] == 'Alice'", "msg": "Alice: 1500 > всех из team 2 (600, 1200)"}],
       ["> ALL — больше всех значений подзапроса"], 3),
    ex(9, "sql", "Найти игроков с score выше среднего по их команде. Используй коррелированный подзапрос.",
       "SELECT p1.name, p1.score FROM players p1 WHERE p1.score > (SELECT AVG(p2.score) FROM players p2 WHERE p2.team_id = p1.team_id);\n",
       "SELECT p1.name, p1.score FROM players p1 WHERE p1.score > (SELECT AVG(p2.score) FROM players p2 WHERE p2.team_id = p1.team_id);",
       [{"check": "len(result) == 2", "msg": "Alice (1500 > 1150) и Diana (1200 > 900)"}],
       ["Коррелированный подзапрос — ссылается на внешний запрос"], 3),
    ex(10, "sql", "Через NOT EXISTS найти игроков, у которых нет team_id в таблице teams (должен быть 0).",
       "SELECT name FROM players p WHERE NOT EXISTS (SELECT 1 FROM teams t WHERE t.id = p.team_id);\n",
       "SELECT name FROM players p WHERE NOT EXISTS (SELECT 1 FROM teams t WHERE t.id = p.team_id);",
       [{"check": "len(result) == 0", "msg": "Все игроки имеют команду"}],
       ["NOT EXISTS — поиск отсутствующих связей"], 2),
]

# ============================================================================
# 2.9 — CTE (2 → 10)
# ============================================================================
EX_2_9 = [
    ex(3, "sql", "Создать CTE для игроков с score > 800 (high_scorers) и выбрать из него всех.",
       "WITH high_scorers AS (SELECT * FROM players WHERE score > 800) SELECT * FROM high_scorers;\n",
       "WITH high_scorers AS (SELECT * FROM players WHERE score > 800) SELECT * FROM high_scorers;",
       [{"check": "len(result) == 3", "msg": "Alice (1500), Diana (1200), Eve (950)"}],
       ["CTE: WITH имя AS (запрос) SELECT"], 2),
    ex(4, "sql", "Создать CTE team_stats, считающую AVG(score) по team_id. Вывести team_id и avg_score.",
       "WITH team_stats AS (SELECT team_id, AVG(score) AS avg_score FROM players GROUP BY team_id) SELECT * FROM team_stats;\n",
       "WITH team_stats AS (SELECT team_id, AVG(score) AS avg_score FROM players GROUP BY team_id) SELECT * FROM team_stats;",
       [{"check": "len(result) == 3", "msg": "3 команды со средними"}],
       ["CTE с агрегатами"], 2),
    ex(5, "sql", "Два CTE: top_players (score > 1000) и team_names (id → team_name). JOIN их.",
       "WITH top_players AS (SELECT name, team_id FROM players WHERE score > 1000), team_names AS (SELECT id, team_name FROM teams) SELECT tp.name, tn.team_name FROM top_players tp JOIN team_names tn ON tp.team_id = tn.id;\n",
       "WITH top_players AS (SELECT name, team_id FROM players WHERE score > 1000), team_names AS (SELECT id, team_name FROM teams) SELECT tp.name, tn.team_name FROM top_players tp JOIN team_names tn ON tp.team_id = tn.id;",
       [{"check": "len(result) == 2", "msg": "Alice (Red) и Diana (Blue)"}],
       ["Несколько CTE через запятую"], 3),
    ex(6, "sql", "CTE с оконной функцией: пронумеровать игроков по убыванию score (ROW_NUMBER).",
       "WITH ranked AS (SELECT name, score, ROW_NUMBER() OVER (ORDER BY score DESC) AS rn FROM players) SELECT * FROM ranked;\n",
       "WITH ranked AS (SELECT name, score, ROW_NUMBER() OVER (ORDER BY score DESC) AS rn FROM players) SELECT * FROM ranked;",
       [{"check": "result[0]['rn'] == 1 and result[0]['name'] == 'Alice'", "msg": "Alice — #1 (1500)"}],
       ["CTE + оконная функция"], 2),
    ex(7, "sql", "CTE top2: выбрать двух игроков с наивысшим score. Потом выбрать только их имена.",
       "WITH top2 AS (SELECT name FROM players ORDER BY score DESC LIMIT 2) SELECT * FROM top2;\n",
       "WITH top2 AS (SELECT name FROM players ORDER BY score DESC LIMIT 2) SELECT * FROM top2;",
       [{"check": "len(result) == 2", "msg": "Alice и Diana"}],
       ["CTE + ORDER BY + LIMIT"], 1),
    ex(8, "sql", "CTE с HAVING: team_stats считает AVG(score) и COUNT(*). Вывести только команды со средним > 900.",
       "WITH team_stats AS (SELECT team_id, AVG(score) AS avg_score, COUNT(*) AS cnt FROM players GROUP BY team_id) SELECT * FROM team_stats WHERE avg_score > 900;\n",
       "WITH team_stats AS (SELECT team_id, AVG(score) AS avg_score, COUNT(*) AS cnt FROM players GROUP BY team_id) SELECT * FROM team_stats WHERE avg_score > 900;",
       [{"check": "len(result) == 1", "msg": "Только team_id=1 (avg 1150)"}],
       ["CTE + WHERE на результат агрегации"], 2),
    ex(9, "sql", "Рекурсивный CTE: сгенерировать последовательность чисел от 1 до 5. (SQLite поддерживает RECURSIVE).",
       "WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM cnt WHERE x < 5) SELECT * FROM cnt;\n",
       "WITH RECURSIVE cnt(x) AS (SELECT 1 UNION ALL SELECT x + 1 FROM cnt WHERE x < 5) SELECT * FROM cnt;",
       [{"check": "len(result) == 5", "msg": "1, 2, 3, 4, 5"}],
       ["RECURSIVE CTE — генерация последовательностей"], 3),
    ex(10, "sql", "CTE team_info с JOIN team_names. Вывести игроков (из players) с их team_name через CTE.",
       "WITH team_info AS (SELECT p.name, p.score, t.team_name FROM players p JOIN teams t ON p.team_id = t.id) SELECT * FROM team_info ORDER BY score DESC;\n",
       "WITH team_info AS (SELECT p.name, p.score, t.team_name FROM players p JOIN teams t ON p.team_id = t.id) SELECT * FROM team_info ORDER BY score DESC;",
       [{"check": "result[0]['name'] == 'Alice'", "msg": "Alice — Red, score 1500"}],
       ["CTE с JOIN + ORDER BY"], 2),
]

# ============================================================================
# 2.10 — Оконные: ROW_NUMBER, RANK, DENSE_RANK (3 → 10)
# ============================================================================
EX_2_10 = [
    ex(4, "sql", "ROW_NUMBER внутри каждой команды по убыванию score. PARTITION BY team_id.",
       "SELECT name, team_id, ROW_NUMBER() OVER (PARTITION BY team_id ORDER BY score DESC) AS rn FROM players;\n",
       "SELECT name, team_id, ROW_NUMBER() OVER (PARTITION BY team_id ORDER BY score DESC) AS rn FROM players;",
       [{"check": "len(result) == 5", "msg": "Каждый игрок пронумерован внутри своей команды"}],
       ["PARTITION BY — окно внутри группы"], 2),
    ex(5, "sql", "RANK по score DESC. Игроки с одинаковым score получают одинаковый ранг.",
       "SELECT name, score, RANK() OVER (ORDER BY score DESC) AS rnk FROM players;\n",
       "SELECT name, score, RANK() OVER (ORDER BY score DESC) AS rnk FROM players;",
       [{"check": "result[2]['rnk'] >= 3", "msg": "Чарли (600) — ранг 5"}],
       ["RANK — пропускает места при совпадениях"], 2),
    ex(6, "sql", "DENSE_RANK по score DESC. Сравни с RANK: DENSE_RANK не пропускает места.",
       "SELECT name, score, DENSE_RANK() OVER (ORDER BY score DESC) AS dr FROM players;\n",
       "SELECT name, score, DENSE_RANK() OVER (ORDER BY score DESC) AS dr FROM players;",
       [{"check": "result[-1]['dr'] == 5", "msg": "5 различных score у 5 игроков"}],
       ["DENSE_RANK — без пропусков"], 2),
    ex(7, "sql", "ROW_NUMBER() OVER (ORDER BY name) — пронумеровать игроков по алфавиту.",
       "SELECT ROW_NUMBER() OVER (ORDER BY name) AS num, name, score FROM players;\n",
       "SELECT ROW_NUMBER() OVER (ORDER BY name) AS num, name, score FROM players;",
       [{"check": "result[0]['name'] == 'Alice'", "msg": "Alice — первая по алфавиту"}],
       ["ROW_NUMBER + ORDER BY name"], 1),
    ex(8, "sql", "Внутри каждой команды (PARTITION BY team_id) пронумеровать по возрастанию score.",
       "SELECT name, team_id, score, ROW_NUMBER() OVER (PARTITION BY team_id ORDER BY score ASC) AS rn FROM players;\n",
       "SELECT name, team_id, score, ROW_NUMBER() OVER (PARTITION BY team_id ORDER BY score ASC) AS rn FROM players;",
       [{"check": "result[0]['rn'] == 1 and result[0]['name'] == 'Bob'", "msg": "Bob — #1 в team 1 (низший score)"}],
       ["PARTITION BY + ORDER BY ASC"], 2),
    ex(9, "sql", "Разница между RANK и DENSE_RANK при одинаковых score. Создай ситуацию с дублями через UNION.",
       "WITH dups AS (SELECT score FROM players UNION ALL SELECT 1500) SELECT score, RANK() OVER (ORDER BY score DESC) AS rnk, DENSE_RANK() OVER (ORDER BY score DESC) AS dr FROM dups;\n",
       "WITH dups AS (SELECT score FROM players UNION ALL SELECT 1500) SELECT score, RANK() OVER (ORDER BY score DESC) AS rnk, DENSE_RANK() OVER (ORDER BY score DESC) AS dr FROM dups;",
       [{"check": "result[0]['rnk'] == 1 and result[0]['dr'] == 1", "msg": "1500 повторяется"}],
       ["Сравнение RANK vs DENSE_RANK с дублями"], 3),
    ex(10, "sql", "ROW_NUMBER() OVER () — без ORDER BY. Порядок не гарантирован, но SQLite вернёт вставленный порядок.",
       "SELECT ROW_NUMBER() OVER () AS num, name FROM players;\n",
       "SELECT ROW_NUMBER() OVER () AS num, name FROM players;",
       [{"check": "result[0]['num'] == 1", "msg": "Первая строка — num=1"}],
       ["ROW_NUMBER без ORDER BY — порядок вставки"], 2),
]

# ============================================================================
# 2.11 — Оконные: LAG, LEAD, SUM OVER (3 → 10)
# ============================================================================
EX_2_11 = [
    ex(4, "sql", "LAG(score, 1, 0) — предыдущий score по убыванию. Если нет предыдущего — 0.",
       "SELECT name, score, LAG(score, 1, 0) OVER (ORDER BY score DESC) AS prev_score FROM players;\n",
       "SELECT name, score, LAG(score, 1, 0) OVER (ORDER BY score DESC) AS prev_score FROM players;",
       [{"check": "result[0]['prev_score'] == 0", "msg": "У Alice (1500) нет предыдущего — 0"}],
       ["LAG(col, offset, default)"], 2),
    ex(5, "sql", "LEAD(score) — следующий score по возрастанию. Сравни с текущим.",
       "SELECT name, score, LEAD(score) OVER (ORDER BY score ASC) AS next_score FROM players;\n",
       "SELECT name, score, LEAD(score) OVER (ORDER BY score ASC) AS next_score FROM players;",
       [{"check": "result[-1]['next_score'] is None", "msg": "У последнего (Alice) нет следующего"}],
       ["LEAD — следующий в окне"], 2),
    ex(6, "sql", "Накопительная сумма score по убыванию score. SUM OVER с ROWS UNBOUNDED PRECEDING.",
       "SELECT name, score, SUM(score) OVER (ORDER BY score DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total FROM players;\n",
       "SELECT name, score, SUM(score) OVER (ORDER BY score DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_total FROM players;",
       [{"check": "result[-1]['running_total'] == 5050", "msg": "Общая сумма — 5050"}],
       ["Накопительная сумма (running total)"], 3),
    ex(7, "sql", "Скользящее среднее за 3 строки: AVG OVER с ROWS 1 PRECEDING AND 1 FOLLOWING.",
       "SELECT name, score, AVG(score) OVER (ORDER BY score DESC ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS moving_avg FROM players;\n",
       "SELECT name, score, AVG(score) OVER (ORDER BY score DESC ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) AS moving_avg FROM players;",
       [{"check": "len(result) == 5", "msg": "Скользящее среднее для каждого игрока"}],
       ["Скользящее среднее (moving average)"], 3),
    ex(8, "sql", "LAG(name) — показать имя предыдущего игрока по score DESC.",
       "SELECT name, score, LAG(name) OVER (ORDER BY score DESC) AS prev_name FROM players;\n",
       "SELECT name, score, LAG(name) OVER (ORDER BY score DESC) AS prev_name FROM players;",
       [{"check": "result[0]['prev_name'] is None", "msg": "У Alice нет предыдущего"}],
       ["LAG с именем — не только числа"], 2),
    ex(9, "sql", "SUM OVER в группе (PARTITION BY team_id). Накопительная сумма score внутри команды.",
       "SELECT name, team_id, score, SUM(score) OVER (PARTITION BY team_id ORDER BY score DESC) AS team_running FROM players;\n",
       "SELECT name, team_id, score, SUM(score) OVER (PARTITION BY team_id ORDER BY score DESC) AS team_running FROM players;",
       [{"check": "len(result) == 5", "msg": "Накопительная сумма по каждой команде"}],
       ["PARTITION BY + SUM OVER — накопление по группам"], 3),
    ex(10, "sql", "AVG OVER для всего окна (без ORDER BY) — средний score по всем строкам повторяется.",
       "SELECT name, score, AVG(score) OVER () AS overall_avg FROM players;\n",
       "SELECT name, score, AVG(score) OVER () AS overall_avg FROM players;",
       [{"check": "result[0]['overall_avg'] == 1010.0", "msg": "1010 — средний score всех"}],
       ["AVG OVER () — общее среднее без группировки"], 2),
]

# ============================================================================
# 2.12 — Оконные: NTILE, PERCENT_RANK (2 → 10)
# ============================================================================
EX_2_12 = [
    ex(3, "sql", "NTILE(2) — разделить игроков на 2 группы по score DESC.",
       "SELECT name, score, NTILE(2) OVER (ORDER BY score DESC) AS grp FROM players;\n",
       "SELECT name, score, NTILE(2) OVER (ORDER BY score DESC) AS grp FROM players;",
       [{"check": "max(r['grp'] for r in result) == 2", "msg": "2 группы: Alice/Diana/Eve — 1, Bob/Charlie — 2"}],
       ["NTILE(2) — две равные группы"], 2),
    ex(4, "sql", "CUME_DIST — кумулятивное распределение score (доля строк с score <= текущего).",
       "SELECT name, score, ROUND(CUME_DIST() OVER (ORDER BY score), 3) AS cd FROM players;\n",
       "SELECT name, score, ROUND(CUME_DIST() OVER (ORDER BY score), 3) AS cd FROM players;",
       [{"check": "result[-1]['cd'] == 1.0", "msg": "Последний (Alice) — 1.0 (100%)"}],
       ["CUME_DIST — процент строк <= текущей"], 3),
    ex(5, "sql", "NTILE(4) — квартили по score DESC. Каждый игрок в одном из 4 сегментов.",
       "SELECT name, score, NTILE(4) OVER (ORDER BY score DESC) AS quartile FROM players;\n",
       "SELECT name, score, NTILE(4) OVER (ORDER BY score DESC) AS quartile FROM players;",
       [{"check": "len(set(r['quartile'] for r in result)) == 4", "msg": "Все 4 квартиля"}],
       ["NTILE(4) — квартили"], 2),
    ex(6, "sql", "PERCENT_RANK с PARTITION BY team_id — позиция игрока внутри команды.",
       "SELECT name, team_id, ROUND(PERCENT_RANK() OVER (PARTITION BY team_id ORDER BY score DESC), 3) AS pr FROM players;\n",
       "SELECT name, team_id, ROUND(PERCENT_RANK() OVER (PARTITION BY team_id ORDER BY score DESC), 3) AS pr FROM players;",
       [{"check": "result[0]['pr'] == 0.0", "msg": "Alice — 0.0 (лучший в team 1)"}],
       ["PERCENT_RANK + PARTITION BY"], 3),
    ex(7, "sql", "NTILE в CTE: создать сегменты, затем отфильтровать только первый сегмент.",
       "WITH seg AS (SELECT name, score, NTILE(3) OVER (ORDER BY score DESC) AS grp FROM players) SELECT name, score FROM seg WHERE grp = 1;\n",
       "WITH seg AS (SELECT name, score, NTILE(3) OVER (ORDER BY score DESC) AS grp FROM players) SELECT name, score FROM seg WHERE grp = 1;",
       [{"check": "result[0]['name'] == 'Alice'", "msg": "Топ-сегмент"}],
       ["NTILE + CTE + фильтр"], 2),
    ex(8, "sql", "NTILE + CASE WHEN: категории 'High' / 'Mid' / 'Low' по третям score.",
       "SELECT name, score, CASE NTILE(3) OVER (ORDER BY score DESC) WHEN 1 THEN 'High' WHEN 2 THEN 'Mid' ELSE 'Low' END AS tier FROM players;\n",
       "SELECT name, score, CASE NTILE(3) OVER (ORDER BY score DESC) WHEN 1 THEN 'High' WHEN 2 THEN 'Mid' ELSE 'Low' END AS tier FROM players;",
       [{"check": "len(result) == 5", "msg": "3 категории по 1-2 игрока"}],
       ["NTILE + CASE — категоризация"], 3),
    ex(9, "sql", "CUME_DIST vs PERCENT_RANK — оба показывают позицию, но считаются по-разному.",
       "SELECT name, score, ROUND(CUME_DIST() OVER (ORDER BY score), 3) AS cd, ROUND(PERCENT_RANK() OVER (ORDER BY score), 3) AS pr FROM players;\n",
       "SELECT name, score, ROUND(CUME_DIST() OVER (ORDER BY score), 3) AS cd, ROUND(PERCENT_RANK() OVER (ORDER BY score), 3) AS pr FROM players;",
       [{"check": "result[0]['cd'] > result[0]['pr']", "msg": "CUME_DIST всегда >= PERCENT_RANK"}],
       ["Сравнение CUME_DIST и PERCENT_RANK"], 3),
    ex(10, "sql", "NTILE(2) по score ASC — деление на две группы (нижняя и верхняя половина).",
       "SELECT name, score, NTILE(2) OVER (ORDER BY score ASC) AS half FROM players;\n",
       "SELECT name, score, NTILE(2) OVER (ORDER BY score ASC) AS half FROM players;",
       [{"check": "result[0]['half'] == 1 and result[0]['name'] == 'Charlie'", "msg": "Charlie (600) — нижняя половина"}],
       ["NTILE + ASC — обратный порядок"], 2),
]

# ============================================================================
# 2.13 — Индексы и EXPLAIN (2 → 10)
# ============================================================================
EX_2_13 = [
    ex(3, "sql", "Создать индекс на столбец name таблицы players для ускорения поиска по имени.",
       "CREATE INDEX IF NOT EXISTS idx_name ON players(name);\n",
       "CREATE INDEX IF NOT EXISTS idx_name ON players(name);",
       [{"check": "'CREATE INDEX' in query.upper() and 'idx_name' in query", "msg": "Индекс idx_name создан"}],
       ["CREATE INDEX — ускоряет WHERE по name"], 2),
    ex(4, "sql", "Создать составной индекс на (team_id, score) для ускорения GROUP BY team_id и ORDER BY score.",
       "CREATE INDEX IF NOT EXISTS idx_team_score ON players(team_id, score);\n",
       "CREATE INDEX IF NOT EXISTS idx_team_score ON players(team_id, score);",
       [{"check": "'CREATE INDEX' in query.upper() and 'idx_team_score' in query", "msg": "Составной индекс"}],
       ["Составной индекс на несколько столбцов"], 2),
    ex(5, "sql", "EXPLAIN QUERY PLAN для запроса SELECT * FROM players WHERE score > 1000.",
       "EXPLAIN QUERY PLAN SELECT * FROM players WHERE score > 1000;\n",
       "EXPLAIN QUERY PLAN SELECT * FROM players WHERE score > 1000;",
       [{"check": "'SCAN' in result[0]['detail'] or 'SEARCH' in result[0]['detail']", "msg": "План выполнения"}],
       ["EXPLAIN QUERY PLAN — как СУБД выполняет запрос"], 2),
    ex(6, "sql", "Создать индекс на score, затем EXPLAIN запроса с WHERE score > 1000. Проверить, что используется индекс.",
       "CREATE INDEX IF NOT EXISTS idx_score ON players(score); EXPLAIN QUERY PLAN SELECT * FROM players WHERE score > 1000;\n",
       "CREATE INDEX IF NOT EXISTS idx_score ON players(score); EXPLAIN QUERY PLAN SELECT * FROM players WHERE score > 1000;",
       [{"check": "len(result) >= 1", "msg": "После CREATE INDEX план может измениться"}],
       ["Индекс + EXPLAIN — оценка эффективности"], 3),
    ex(7, "sql", "Удалить индекс idx_score, если он существует, через DROP INDEX.",
       "DROP INDEX IF EXISTS idx_score;\n",
       "DROP INDEX IF EXISTS idx_score;",
       [{"check": "'DROP INDEX' in query.upper()", "msg": "Индекс удалён"}],
       ["DROP INDEX — удаление индекса"], 2),
    ex(8, "sql", "EXPLAIN запроса с JOIN: SELECT p.name, t.team_name FROM players p JOIN teams t ON p.team_id = t.id.",
       "EXPLAIN QUERY PLAN SELECT p.name, t.team_name FROM players p JOIN teams t ON p.team_id = t.id;\n",
       "EXPLAIN QUERY PLAN SELECT p.name, t.team_name FROM players p JOIN teams t ON p.team_id = t.id;",
       [{"check": "len(result) >= 1", "msg": "План выполнения JOIN"}],
       ["EXPLAIN JOIN — план соединения таблиц"], 2),
    ex(9, "sql", "Объяснить (через комментарий в SQLite) разницу между SCAN и SEARCH в плане выполнения. Создать индекс и показать SEARCH.",
       "CREATE INDEX IF NOT EXISTS idx_score ON players(score); EXPLAIN QUERY PLAN SELECT * FROM players WHERE score = 950;\n",
       "CREATE INDEX IF NOT EXISTS idx_score ON players(score); EXPLAIN QUERY PLAN SELECT * FROM players WHERE score = 950;",
       [{"check": "len(result) >= 1", "msg": "Индекс для поиска по точному значению"}],
       ["SEARCH — поиск по индексу"], 3),
    ex(10, "sql", "EXPLAIN запроса с GROUP BY team_id. Показать, что GROUP BY требует сортировки.",
       "EXPLAIN QUERY PLAN SELECT team_id, COUNT(*) FROM players GROUP BY team_id;\n",
       "EXPLAIN QUERY PLAN SELECT team_id, COUNT(*) FROM players GROUP BY team_id;",
       [{"check": "len(result) >= 1", "msg": "План выполнения GROUP BY"}],
       ["EXPLAIN GROUP BY — понимание агрегации"], 2),
]

# ============================================================================
# 2.14 — Мини-проект: Аналитика игровой платформы (3 → 10)
# ============================================================================
EX_2_14 = [
    ex(4, "sql", "LEFT JOIN sessions к players. Вывести имя игрока и количество его сессий. Отсортировать по убыванию.",
       "SELECT p.name, COUNT(s.id) AS sessions_cnt FROM players p LEFT JOIN sessions s ON p.id = s.player_id GROUP BY p.id ORDER BY sessions_cnt DESC;\n",
       "SELECT p.name, COUNT(s.id) AS sessions_cnt FROM players p LEFT JOIN sessions s ON p.id = s.player_id GROUP BY p.id ORDER BY sessions_cnt DESC;",
       [{"check": "len(result) == 5", "msg": "Каждый игрок с количеством сессий"}],
       ["LEFT JOIN + COUNT"], 2),
    ex(5, "sql", "Через CTE и JOIN: найти игроков, которые сделали хотя бы одну покупку. Используй EXISTS.",
       "SELECT p.name, p.score FROM players p WHERE EXISTS (SELECT 1 FROM purchases pu WHERE pu.player_id = p.id);\n",
       "SELECT p.name, p.score FROM players p WHERE EXISTS (SELECT 1 FROM purchases pu WHERE pu.player_id = p.id);",
       [{"check": "len(result) == 5", "msg": "Все игроки делали покупки"}],
       ["EXISTS + подзапрос к purchases"], 2),
    ex(6, "sql", "Для каждого игрока вывести общую сумму покупок. Если покупок не было — 0. Используй COALESCE.",
       "SELECT p.name, COALESCE(SUM(pu.amount), 0) AS total_spent FROM players p LEFT JOIN purchases pu ON p.id = pu.player_id GROUP BY p.id ORDER BY total_spent DESC;\n",
       "SELECT p.name, COALESCE(SUM(pu.amount), 0) AS total_spent FROM players p LEFT JOIN purchases pu ON p.id = pu.player_id GROUP BY p.id ORDER BY total_spent DESC;",
       [{"check": "len(result) == 5", "msg": "Сумма трат по каждому игроку"}],
       ["LEFT JOIN + SUM + COALESCE"], 2),
    ex(7, "sql", "Используя UNION ALL, объединить имена игроков и названия команд в один список.",
       "SELECT name AS entity FROM players UNION ALL SELECT team_name FROM teams;\n",
       "SELECT name AS entity FROM players UNION ALL SELECT team_name FROM teams;",
       [{"check": "len(result) == 8", "msg": "5 + 3 = 8 строк"}],
       ["UNION ALL — объединение результатов"], 2),
    ex(8, "sql", "Создать представление (CREATE VIEW) top_players для игроков со score > 1000.",
       "CREATE VIEW IF NOT EXISTS top_players AS SELECT * FROM players WHERE score > 1000;\n",
       "CREATE VIEW IF NOT EXISTS top_players AS SELECT * FROM players WHERE score > 1000;",
       [{"check": "'CREATE VIEW' in query.upper()", "msg": "View создано"}],
       ["CREATE VIEW — виртуальная таблица"], 2),
    ex(9, "sql", "Оконная функция в мини-проекте: ROW_NUMBER игроков по общей сумме покупок (через JOIN с purchases).",
       "SELECT p.name, SUM(pu.amount) AS total, ROW_NUMBER() OVER (ORDER BY SUM(pu.amount) DESC) AS rn FROM players p JOIN purchases pu ON p.id = pu.player_id GROUP BY p.id;\n",
       "SELECT p.name, SUM(pu.amount) AS total, ROW_NUMBER() OVER (ORDER BY SUM(pu.amount) DESC) AS rn FROM players p JOIN purchases pu ON p.id = pu.player_id GROUP BY p.id;",
       [{"check": "len(result) == 5", "msg": "Игроки отсортированы по сумме трат"}],
       ["Оконная + агрегат + JOIN"], 3),
    ex(10, "sql", "Финальный аналитический запрос: CTE + JOIN + оконная функция. Топ-3 игрока по сумме покупок.",
       "WITH spending AS (SELECT p.name, SUM(pu.amount) AS total FROM players p JOIN purchases pu ON p.id = pu.player_id GROUP BY p.id) SELECT name, total, RANK() OVER (ORDER BY total DESC) AS rnk FROM spending LIMIT 3;\n",
       "WITH spending AS (SELECT p.name, SUM(pu.amount) AS total FROM players p JOIN purchases pu ON p.id = pu.player_id GROUP BY p.id) SELECT name, total, RANK() OVER (ORDER BY total DESC) AS rnk FROM spending LIMIT 3;",
       [{"check": "len(result) == 3", "msg": "Топ-3 по тратам"}],
       ["CTE + оконная + LIMIT — аналитический запрос"], 3),
]

# ============================================================================
# Словарь: номер урока → список доп. упражнений
# ============================================================================
EXTRA_EXERCISES = {
    "2.1": EX_2_1,
    "2.2": EX_2_2,
    "2.3": EX_2_3,
    "2.4": EX_2_4,
    "2.5": EX_2_5,
    "2.6": EX_2_6,
    "2.7": EX_2_7,
    "2.8": EX_2_8,
    "2.9": EX_2_9,
    "2.10": EX_2_10,
    "2.11": EX_2_11,
    "2.12": EX_2_12,
    "2.13": EX_2_13,
    "2.14": EX_2_14,
}
